# Generated by Django 4.2.13 on 2024-05-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_speaker': True}, related_name='events', to='meetup.userprofile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_questions', to='meetup.userprofile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to='meetup.userprofile'),
        ),
    ]
