# Generated by Django 4.2.13 on 2024-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_remove_report_created_at_report_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='events', to='meetup.userprofile'),
        ),
    ]
